code/modules/uplink/uplink_items.dm
**Cuts the price of PML-9 ammo in half!**
- the HE rocket went from 4 to 2 TC
- the HEDP rocket went from 6 to 3 TC
The PML-9 is just like some other nukie weapons, overshadowed by the better options such as the L6 or M90-GL.
This is mainly because of the fact that the L6 and M90 are capable of quickly and effortlessly killing people, whereas the PML-9 has several dangers tied to it while being very ammo-inefficient.
This change aims to make the PML-9 a more relevant nukie weapon, so operatives who like explosives won't shy away from it due to better options being available while the crew gets to see more variety in operatives.
:cl:
balance: PML-9 rocket prices are cut in half due to the supply far exeeding its demand...
/:cl:
=> Lowers the price of rocket launcher ammo.

code/game/objects/items/storage/backpack.dm, code/game/objects/items/storage/uplink_kits.dm, code/modules/uplink/uplink_items.dm
**Adds an explosives bundle for nuclear operatives, it contains:**
- PML-9 Rocket Launcher
- Grenadier's Belt
- 84mm Rocket Ammunition Box
- Havanian cigars, a matchbox, orange sunglasses and a syndie HoS cap.
**Also adds a Rocket Ammunition Box, it contains:**
- Six HE rockets
- Two solid fuel canisters
- One HEDP rocket
This was done as a love letter to people who like explosives, giving them access to a fun bundle while also introducing the classic _Cuban dictator with a rocket launcher_ bad guy.
=> Adds the Explosives bundle (and a rocket ammo box) for nukies.

code/modules/research/designs/wiremod_designs.dm, code/modules/research/techweb/all_nodes.dm, code/modules/wiremod/shell/mech.dm, code/modules/wiremod/shell/shell_items.dm, tgstation.dme
You can turn any mech into a circuit mech using a researchable mech interface, printable at the protolathe or component printer.
Doing so is irreversible and takes 8 seconds. It also adds "-Circuitix" by default to the mech's name, though you can still change it by climbing in.
You can still use it as normal, but it can now be occupied by integrated circuits, which prevent you from entering them. You can screwdriver them out to be able to climb in again, of course.
The circuit placed inside a circuit mech can move it around, cycle equipment and use currently selected equipment to attack. It can't use radial menus or anything of course.
Because autonomous mechs are funny and balanced.
:cl:
add: All mechs can now be upgraded to be able to take a circuit as a controller/occupant. Nanotrasen …
=> Add circuit mechs

code/__HELPERS/sanitize_values.dm, code/modules/client/preferences.dm
Removes the non-binary option, IDpol and neurotypicals have no place in a 2D spaceman game where you beat eachother in the head with toolboxes.
=> Removes degeneracy.

code/__DEFINES/cult.dm, code/modules/antagonists/cult/blood_magic.dm, code/modules/antagonists/cult/runes.dm
This PR is created to balance Cultists in Low-Pop format, this is the start to sorting out the bigger issues, but obviously testing will be needed before hitting the rest of the Cultist items, runes, and spells.
A Cultist can only have 3 spells on them with a spell rune, instead of 4.
First, the cultist rate needed to obtain the red halo goes from 40% to 30% so that security can quickly notice the problem, to 40%, cultists will clearly outnumber the unconverted crew!
Then, the Blood Rite spell was well modified, the blood collected on the ground and a living carbon were (approximately) multiplied by two, making it possible to use the spell without needing to slaughter many NPC carbons.
You also need 25 Iron instead of 50 to make construct shells.
The Stun and Shackles spells have been …
=> Converting Cultists to Low Pop

code/modules/antagonists/cult/cultlowpopdocumentation.md
It turns out having a **documentation** for this balancing change is **important**, so that if we were to switch back to the normal high pop format, we can use the documentation to revert all needed lines!
So as requested, I have put a .md file in the antag cult folder for future read and use. Should I make more balance changes in the future, the documentation will be updated.
Tracking my bullshit : Good for my memory and future coders. 
:cl:
add: Documentation added in code\modules\antagonists\cult
/:cl:
=> Documentation for Cultist Low Pop Balance Changes

code/game/objects/structures/window.dm
Same as the last one
Reinforced windows were just too durable for the materials needed to make them.
:cl:
-Damage reduction removed from rwindows
-Melee armor of rwindow reduced from 80 to 50
-Steps to unsecure an rwindow has been reduced
-You now need to screwdriver, crowbar and then wrench the window to remove it
-Plasma windows are unchanged and still use the previous rwindow method of removal
/:cl:
=> Nerfs Reinforced Windows

code/game/objects/items/card_access_chips.dm, code/game/objects/items/cards_ids.dm, code/modules/mining/machine_vending.dm
mining IDs now have the correct assignment, also conscription kit has an AA-chip for mining access instead of an ID.
=> fix mining IDs

_maps/RandomRuins/IceRuins/icemoon_surface_engioutpost.dmm, _maps/RandomRuins/SpaceRuins/TheDerelict.dmm, _maps/RandomRuins/SpaceRuins/forgottenship.dmm, _maps/RandomRuins/SpaceRuins/oldstation.dmm, _maps/RandomZLevels/undergroundoutpost45.dmm, code/__DEFINES/machines.dm, code/game/objects/items/circuitboards/machine_circuitboards.dm, code/game/objects/items/storage/boxes.dm, code/modules/mining/lavaland/necropolis_chests.dm, code/modules/research/designs.dm, code/modules/research/designs/autolathe_designs.dm, code/modules/research/designs/bluespace_designs.dm, code/modules/research/designs/comp_board_designs.dm, code/modules/research/designs/computer_part_designs.dm, code/modules/research/designs/electronics_designs.dm, code/modules/research/designs/experisci_designs.dm, code/modules/research/designs/machine_designs.dm, code/modules/research/designs/mecha_designs.dm, code/modules/research/designs/medical_designs.dm, code/modules/research/designs/mining_designs.dm, code/modules/research/designs/misc_designs.dm, code/modules/research/designs/power_designs.dm, code/modules/research/designs/smelting_designs.dm, code/modules/research/designs/stock_parts_designs.dm, code/modules/research/designs/tool_designs.dm, code/modules/research/designs/weapon_designs.dm, code/modules/research/machinery/circuit_imprinter.dm, code/modules/research/machinery/protolathe.dm, code/modules/research/rdconsole.dm, code/modules/research/techweb/all_nodes.dm
Removes offstation variants and replaces them with the normal ones.
Essentially reverts: https://github.com/tgstation/tgstation/pull/57367
For us, SS13 is an off-rails game with an arcade-like setting. So in order to increase the fun and potential of rounds we're better off giving ghost roles more tools to interact with the round itself while allowing them to come up with more ideas of their own.
=> Single protolathe / circuit imprinter.

code/modules/power/singularity/emitter.dm
the check in proc/update_icon_state didn't match the check in proc/process
closes #71
=> fix emitter icon_state not updating correctly when out of power.

code/modules/atmospherics/machinery/pipes/smart.dm
(Partially?) Fixes #84 because I don't need to do a complicated revert when I can make them work just fine.
If you still have issues then consider you might have an unironic skill issue.
Being able to properly map smart pipes next to each other so they don't connect when you don't want them to is a pretty useful thing to have. Somebody who shall not be named who implemented them did not do his due diligence in making sure the mapping helpers worked correctly, and an unnamed maintainer merged it. 
:cl:
fix: Fixed tg's mess with smart pipes. Shame on you.
/:cl:
=> Fixes mapped smart pipes connecting incorrectly

_maps/RandomRuins/SpaceRuins/DJstation.dmm, _maps/RandomRuins/SpaceRuins/TheDerelict.dmm, _maps/RandomRuins/SpaceRuins/abandonedzoo.dmm, _maps/RandomRuins/SpaceRuins/bigderelict1.dmm, _maps/RandomRuins/SpaceRuins/caravanambush.dmm, _maps/RandomRuins/SpaceRuins/crashedship.dmm, _maps/RandomRuins/SpaceRuins/deepstorage.dmm, _maps/RandomRuins/SpaceRuins/gasthelizards.dmm, _maps/RandomRuins/SpaceRuins/mrow_thats_right.dmm, _maps/RandomRuins/SpaceRuins/onehalf.dmm, _maps/RandomRuins/SpaceRuins/originalcontent.dmm, _maps/RandomRuins/SpaceRuins/spacehotel.dmm, _maps/RandomRuins/SpaceRuins/turretedoutpost.dmm, _maps/RandomRuins/SpaceRuins/whiteshipruin_box.dmm, _maps/shuttles/whiteship_box.dmm, _maps/shuttles/whiteship_cere.dmm, _maps/shuttles/whiteship_delta.dmm, _maps/shuttles/whiteship_donut.dmm, _maps/shuttles/whiteship_kilo.dmm, _maps/shuttles/whiteship_meta.dmm, _maps/shuttles/whiteship_pubby.dmm, _maps/shuttles/whiteship_tram.dmm, code/game/objects/items/circuitboards/computer_circuitboards.dm, code/modules/shuttle/white_ship.dm
The Whiteships now have their own GPS signals.
Good space loot has been re-added.
This isn't the final change, but it's a good start to adjusting things for our codebase.
In the final PR, i'll most likely make all signals (except the whiteships) have a spaceruin signal, while in turn making sure every ruin will be worth visiting to some degree.
=> Buffs space loot, gives whiteship it's own GPS.

code/game/objects/items/storage/briefcase.dm, code/modules/surgery/organs/cybernetics/augments_arms.dm, code/modules/uplink/uplink_items.dm
Fixes laser arm having wrong hacking protocols and bundles it with a syndicate cyberlink
:cl:
add: Laser arm  now comes bundled with  syndicate cyberlink
fix: Laser arm now has syndicate hacking protocols instead of Terragov ones
/:cl:
=> Fixes Laser arm cybernetics containing wrong protocols, and bundles it together with a syndicate cyberlink

code/modules/vending/wardrobes.dm
What the title says
Let's science have access to plain white lab coats again in case people didn't care for the new trimmed coats.
:cl:
Adds 2 plain coats to the Robo vendor and 5 to the standard Sci vendor
/:cl:
=> Adds Standard Lab Coats to Sci Vendors

code/modules/ruins/lavalandruin_code/sloth.dm
Sets the text in the right place for once.
This is absolutely VITAL to the core gameplay loop. If you do not believe me, you can try this homebrew experiment!
You will need:
Step one: power the vacuum cleaner
Step two: stick it where the sun doesn't shine
Step three: now that the sand is out of your ass, you are inclined to agree that this change is mandatory!
=> Fixes sloth note.

_maps/map_files/MetaStation/MetaStation.dmm
The primary treatment center in the medbay has had all the junk in the middle stripped out, and in its place, 4 more wards for waiting patients have been added. Minor tweaks have also been made to the Primary Surgical Theatre and other neighboring rooms in order to make them function better alongside the revamped medbay.
Medbay on highpop or just very active rounds can end up as a massive mess, with even four fully setup stasis beds/operating tables with operating computers often not being able to pick up the slack. These extra wards, while not pretty, are very functional, giving ample room to set up a full operating theatre for a patient to be worked on, with room to install the medical devices mentioned just before.
:cl:
add: Added MetaStation medbay wards
qol: Put the surgical tools in …
=> Strip down the Primary Treatment Center on MetaStation and add more wards

code/game/objects/structures/crates_lockers/closets/secure/medical.dm, code/modules/surgery/organs/cybernetics/augments_eyes.dm
Eyes didnt have proper update logic in em. 
Also adds NT1.0 cyberlink autosurgeon to CMO's office
:cl:
fix: Fixed eye implant auto-update logic
add: CMO's locker now spawns with NT1.0 cyberlink autosurgeon
/:cl:
=> Fixes eye cybernetics sometimes not working when installed in the wrong order, also adds NT cyberlink autosurgeon to CMO's office

code/game/objects/items/devices/radio/headset.dm, code/game/objects/items/devices/radio/radio.dm, code/modules/mob/living/carbon/human/human_say.dm
This PR allows station-bounced radios to broadcast messages on the subspace network (making them no longer station-bounced radios), allows encryption keys to be installed into them, and allows speaking into radios held in your hand without turning on the microphone.
This makes hand radios more than a toy, and also introduces them as a potential viable alternative to headsets, for cosmetic purposes.
:cl:
add: Allows radios to be spoken into when in hand without their microphones being enabled
expansion: Station-bounced radios now communicate on subspace network, can have encryption keys added and removed
del: hand radios can no longer be attached to things, though afaik they couldn't be used for grenades or TTVs anyway
code: combined a lot of headset code with radio code
code: hands are …
=> Hand Radio Update - Station-Bounced radio now functionally similar to a headset

code/modules/vending/cigarette.dm
Adds syndicate cigarette packets to the contraband catalogue of cigarette vending machines (vending machines must be hacked in order to show these cigarettes available for sale).
It's cool. (Omnizine is readily available anyways through donk pockets anyways).
:cl:
add: Adds syndicate cigarette packets to the contraband catalogue of cigarette vending machines.
/:cl:
=> Add syndicate cigarettes to the contraband of cigarette vending machines

code/modules/mob/living/carbon/human/human_say.dm
The lines that are removed `if(held)` are redundant, because `for(var/obj/item/radio/held in held_items)` already typechecks the object being iterated.
These changes don't conflict with the one in the other radio refactoring PR.
:cl:
refactor: Remove redundant check for talking into radios held in hand
/:cl:
=> Remove redundant check for talking into radios held in hand

code/game/machinery/civilian_bounties.dm, code/game/objects/items/devices/radio/headset.dm, code/game/objects/items/devices/radio/radio.dm, code/game/objects/items/implants/implant_misc.dm, code/modules/admin/verbs/borgpanel.dm, code/modules/antagonists/abductor/equipment/abduction_gear.dm, code/modules/atmospherics/machinery/components/fusion/hfr_core.dm, code/modules/atmospherics/machinery/components/unary_devices/cryo.dm, code/modules/clothing/outfits/ert.dm, code/modules/jobs/job_types/security_officer.dm, code/modules/mob/living/silicon/robot/robot.dm, code/modules/mob/living/simple_animal/bot/bot.dm, code/modules/power/supermatter/supermatter.dm
Replaces the keyslot and keyslot2 variables in radios with a list called keyslots. Also makes all radios only accept one encryption key by default (as opposed to the 0 that was allowed before my previous PR).
Makes the code for adding and removing encryption keys from a radio/headset much cleaner, and can scale to allow for radios with more (or less) maximum allowed encryption keys.
:cl:
refactor: replaced keyslot and keyslot2 vars with keyslots list
balance: made radios accept only 1 encryption key by default (except for headsets)
/:cl:
=> Radio Encryption Key Refactor

code/game/objects/items/devices/radio/headset.dm
Fixes the initialization of ERT headsets to have the CentCom encryption key, which was accidentally removed in the previous refactor PR.
:cl:
fix: Readds the CentCom encryption key to ERT headsets
/:cl:
=> Readds the CentCom encryption key to ERT headsets

code/modules/uplink/uplink_items.dm
Increases the price of the traitor uplink wrestling belt to 17 tc
Instant aggro grab, old stuns and you can still use guns. This used to be a tc trade for a reason and if we're going to put it in the uplink then it's going to cost at least as much as old sleeping carp.
The belt now costs 17 tc instead of a insanely low 8 tc
=> Increase wrestle belt tc cost

dependencies.sh
Downgrades the node.js dependency from 16.14 to 16.13, which is the latest version Rocky Linux 8 is compatible with.
The server works again.
:cl:
fix: Downgraded node dependency to match RL8 package (16.14.2 -> 16.13.1)
/:cl:
=> Downgraded node dependency to match RL8 package

code/controllers/configuration/entries/dbconfig.dm, code/controllers/subsystem/dbcore.dm, config/dbconfig.txt, dependencies.sh
Allows the server to encrypt SQL queries in TLS, making communication between the game server and SQL server over the internet more secure
:cl:
add: Added MariaDB TLS support
/:cl:
=> Adds SSL Support for the server's MariaDB Database

dependencies.sh
TGS gets its own version of node when compiling, so we're not held back by whatever version Rocky Linux officially supports
:cl:
server: Updates Node LTS again to latest version
/:cl:
=> Updates Node LTS again to latest version

code/modules/surgery/organ_manipulation.dm
Fix not being able to do organ manipulation on your legs
We have leg-inserted cybernetic implants, but we had no organ manipulation surgery for the legs, rendering the implants useless. Not anymore.
:cl:
add: Station surgeons have finally been trained in the insertion and removal of leg-inserted cybernetic implants.
/:cl:
=> Surgery hotfix

code/controllers/configuration/entries/general.dm, config/config.txt
We still have /tg/'s links as default for Discord Invites, website and the wiki. This fixes that.
:cl:
config: Changed config URLs to use merchant station links
/:cl:
=> Changed config URLs to use merchant station links [ci skip]

code/modules/research/designs/autolathe_designs.dm
That's right, this PR re-adds shotgun shells and slugs to the hacked autolathe. Shouldn't be a problem since they aren't as batshit insane as before.
Also, laser shells can now only be printed from seclathes.
:cl:
add: Shotgun shells and slugs can now be printed from hacked autolathes again.
/:cl:
=> Re-adds buckshot and slugs to the hacked autolathe.

code/modules/deathmatch/deathmatch_maps.dm
All the deathmatch maps now require only two players to start.
The two maps currently locked to 4 players - Maint Mania and Brig, work perfectly fine with only two players fighting.
Maint Mania is based on the dark dingy tunnels of maintenance and rewards situational awareness, but also the map is compact enough to allow two players to easily find each other and brawl it out.
Brig is just the Metastation brig and I don't see how it exactly requires 4 players to fight.
Case in point, this server does not get much pop anyway and arbitrarily locking off two of the maps (one of which is just AMAZING) seems nonsensical.
:cl: averagejoe22
tweak: All deathmatch maps now only require 2 players to start
/:cl:
=> Makes the minimum required players for all deathmatch maps 2

code/game/machinery/computer/Operating.dm, code/game/machinery/stasis.dm, code/modules/surgery/surgery.dm
Undoes tgstation/tgstation#57306 and part of tgstation/tgstation#59371
> Medical literally always moves the computers to the stasis beds, bypassing operating tables almost completely.
So? (There's only two of them roundstart on Meta anyways and we've got way more than 2 surgery tables/beds now)
> Stasis beds are not meant to be THE medical tool, yet they currently are.
They replaced sleepers, which WERE the medical tool. And who the fuck are you to judge? You're a sci player
> With this change, operating tables and stasis beds will each have their own niche
2 stasis beds is not enough of a fucking corpse queue to be a "niche"
> and it will hopefully provide a bit more diversity in how medical treat patients.
so you nerf the shit out of chems to make surgery viable, and then you nerf …
=> Makes operating computers work with stasis beds again

code/modules/power/singularity/singularity.dm
Makes the singularity actually emit radiation again; was removed in the same PR that removed the singulo and tesla for power generation (tgstation/tgstation#52873).
ALL HAIL LORD SINGULOTH
:cl:
balance: The singulo can now be used for power generation again
/:cl:
=> Makes the singulo work for power generation again

code/modules/cargo/packs.dm
basnnga
:cl:
balance: Nullcrate production is in FULL swing. They are way easier to get now!
/:cl:
=> Makes Null_crates cheaper by a factor of three

code/datums/view.dm, code/modules/client/client_defines.dm, code/modules/client/client_procs.dm, code/modules/client/verbs/ooc.dm
Ports tgstation/tgstation#65225, kitbashes it a bit. Also worth noting that this fixes the width of the viewport when using pixel perfect scaling (like I do).
Before fix (Pixel Perfect 2x, Nearest Neighbor):
After fix:
Notice how the fitted viewport no longer has horizontal letterboxing (the vertical letterboxing, unfortunately, is inherent to using 2x pixel perfect scaling at 1080p. such is life)
I don't have to pixel hunt after horizontal letterboxing of the viewport now (JK I never did because I'm lazy)
:cl:
fix: Fixes automatic viewport fitting
/:cl:
=> Fixes automatic viewport fitting

code/__HELPERS/mobs.dm, code/modules/reagents/chemistry/reagents/other_reagents.dm, code/modules/surgery/bodyparts/helpers.dm
The sign is a subtle joke. The shop is called "Sneed's Feed & Seed", where feed and seed both end in the sound "-eed", thus rhyming with the name of the owner, Sneed. The sign says that the shop was "Formerly Chuck's", implying that the two words beginning with "F" and "S" would have ended with "-uck", rhyming with "Chuck". So, when Chuck owned the shop, it would have been called "Chuck's Fuck and Suck".
:cl:
add: Well well, Look at the city slicker pulling up in his fancy German car
/:cl:
=> Adds simpson skintone

SQL/database_changelog.txt, SQL/tgstation_schema.sql, code/__DEFINES/subsystems.dm, code/controllers/subsystem/blackbox.dm, code/controllers/subsystem/dbcore.dm
Officially updates the datatype for ban reasons from `VARCHAR(2048)` to `TEXT` increasing the effective character limit to ~64,000. Also changes the backend DB feedback table from MyISAM (fucking ancient and not crash resistant) to MyRocks (fast writes, low write amplification, fast for SSDs).
(Yes I'm gonna merge this myself. Not like you potatoes know SQL anyways.)
Database won't shit itself on crash (not like this has happened before).
:cl:
admin: Ban reasons can now be WAY longer (hopefully it doesn't break ban reason display for the banned users)
server: Optimized database schema
/:cl:
=> database shenanigans, nothing to see here folks

code/datums/components/storage/storage.dm, code/game/objects/structures/flora.dm
Adds ability to stash normal-sized items in potted plants.
Made small change to /datum/component/storage.  Adds an option to disable item inserting if storage inventory is not open.
Was required for potted plant stashing to avoid accidental item stashing. This option is set to false by default.
More creative ways of hiding items.
:cl:
add: Add ability to stash normal-sized items in potted plants.
code: Added new variable insert_while_closed to /datum/component/storage.
/:cl:
=> Add ability to stash normal-sized items in potted plants.

code/modules/cargo/packs.dm
Reverts The-Merchants-Guild/Merchant-Station-13#200
God damn. It was obvious that this was gonna make surplus crates more common, but virtually every round a cargo or QM has tator, they just emag the console and buy money briefcases and get more shit than a warops nukie.
🆑
balance: Due to the sudden uptick in demand, the price on surplus crates has been reinflated.
/🆑
=> Revert "Makes Null_crates cheaper by a factor of three"

code/modules/uplink/uplink_items.dm
Restricts the High Frequency blade to the Roboticist and the Research Director until Buco reworks it.
Role Restricts the High Frequency blade to the Roboticist and the Research Director in the Syndicate Uplink until Buco can rework it.
This thing gets spammed every other round and everyone complains about it.
:cl:
balance: rebalanced something
/:cl:
=> High Frequency Blade Role Restrict

_maps/map_files/DM/Maint_Mania.dmm, _maps/map_files/DM/OSHA_Violator.dmm
why didn't you make them indestructible windows from the start REEEEEEEEEE
:cl:
fix: Can't get to CC from the deathmatch map. Also removed the singularity/tesla from OSHA violator for obvious reasons.
/:cl:
=> Fixes escaping the DM(I hope)

code/datums/materials/basemats.dm, code/game/objects/effects/decals/cleanable/robots.dm, code/game/objects/effects/effect_system/effects_foam.dm, code/game/objects/items/clown_items.dm, code/game/objects/items/devices/PDA/PDA_types.dm, code/game/objects/items/food/bread.dm, code/game/objects/items/food/meat.dm, code/modules/antagonists/clown_ops/clown_weapons.dm, code/modules/hydroponics/grown/banana.dm, code/modules/hydroponics/plant_genes.dm
TG MAKING SLIPS NO LONGER ACTUALLY STUN HAS GOT TO HAVE BEEN THE DUMBEST DECISION THEY HAVE EVER MADE, THEREFORE, I AM BRINGING BACK THE GOOD OLD DAYS.
:cl:
balance: Slips stun you again. God's in his Heaven, all is right with the world.
/:cl:
=> SLIPS HARDSTUN AGAIN

code/game/objects/items/grenades/chem_grenade.dm, code/modules/reagents/chemistry/recipes.dm
Fixes a few minor minor bugs regarding chemnades as well as chemical explosions inside a player's stomach. Also allows plastic bottles to be used in chemnades (as well as fixing non-beaker reagent containers working in large nades). Shout out to @NonCoderAlias for pointing these out.
Being able to build ghetto nades out of plastic sheets and metal should be more accessible to other players. While assistants should never be able to get items as powerful as endgame departments, they should still be able to have a fair bit of freedom with what arms they can amass.
:cl:
balance: Plastic bottles can now be used in chemical grenades.
fix: Alternate reagent containers now work in large grenades again.
fix: Chemical explosions now work in the stomach again (this was not a rebalance, it generated …
=> A few small chem fixes

code/controllers/configuration/entries/general.dm, code/game/objects/items/manuals.dm, config/config.txt, interface/interface.dm
Fixes wikibooks. This isn't totally our fault; /tg/station's wiki installation is the improperly done one.
:cl:
fix: Fixes wikibooks
/:cl:
=> Fix Wikibooks

.vscode/extensions.json, .vscode/settings.json
Here you go Etra
Adds Anturk DMI to vscode setup
It's a purely coder-oriented change, doesn't change compilation, just makes it so you can stare at dmis in vscode with extra things to help you out instead of having to open dreammaker and break your dme
=> Anturk dmi change as separate PR

code/__DEFINES/id_cards.dm
Matches the limit on access per card to the amount of access station has overall.
Does the same for common ID card, making silver and common card distinct only visually.
Additionally removes limits from chameleon card
I don't know.
:cl:
balance: Silver and Regular id cards now have same access limits.
balance: Removed limits on chameleon card.
/:cl:
=> Uplifts the limit on the cards

code/modules/antagonists/nukeop/equipment/nuclearbomb.dm
https://github.com/tgstation/tgstation/pull/62807
:cl:
add: The Nanotrasen High Impact Weapons Division would like to apologize for manufacturing a large quantity of dud onboard nuclear warheads. Following a recall, we expect that the replacement batch of warheads will be 900% more likely to Anhilate all life within its radius.
/:cl:
=> Nuke actually kills people now

code/datums/martial/krav_maga.dm
Removes the special disarm interactions from Krav Maga and also fixes up the messages in chat.
Okay, the text changes are just there because it's really grating when being unable to use Krav Maga moves while incapacitated for some reason outputs the entire name of the move AND it's description. The [name]s used in the text have just been replaced with the name of the move so it looks nicer. I'm fairly sure this is the intended behavior and no one just bothered to update this because selecting moves just uses it's name without the long spammy description.
The part everyone cares about is, of course, the practical changes to Krav Maga disarms. The reason this was changed is simple. Presently, Krav Maga disarms **SUCK ASS**. It deals a minor random amount of stamina damage and has a chance …
=> Krav Maga changes

code/datums/components/wet_floor.dm, code/game/turfs/open/_open.dm
I WARNED YOU ABOUT THEM STUNS MAYNE
:cl:
add: Wet floor slips stun you like every other slip now.
add: Lube tiles make you slip from other lube tiles, making it possible to get chainlubed. 
/:cl:
=> Wet floor slips ALSO stun you, and if you go into another lube tile once lubed already, you go forward more

code/modules/events/patient_zero.dm, tgstation.dme
Adds Patient Zero, a midround zombie antag thrown at your station from space.
Zombie rounds can be fun.
:cl:
add: Midround Antag Patient Zero Random Event
/:cl:
=> Midround Antag - Patient Zero

code/game/objects/items/holosign_creator.dm, code/modules/mob/living/silicon/robot/robot_modules.dm
Gives Engiborgs ATMOS holofan barrier projectors . Adds a specific variant for them that has 12 charges instead of 6.
Engiborgs can now do more to help with breaches, fires, and gas leaks. They can also build wacky stuff like Plasmamen habitats easier.
:cl:
add: Engineering borgs now start with ATMOS holofan projectors
/:cl:
=> Gives Engiborgs ATMOS holofan barrier projectors

code/_globalvars/lists/maintenance_loot.dm, code/game/objects/structures/crates_lockers/closets/secure/medical.dm, code/modules/jobs/job_types/chemist.dm, code/modules/reagents/reagent_containers/bottle.dm
They are literally useless.
:cl:
del: Removed chemical buffer bottles as the PH doesn't matter.
/:cl:
=> Removes chemical buffer bottles.

code/modules/atmospherics/machinery/datum_pipeline.dm, code/modules/reagents/chemistry/machinery/chem_dispenser.dm, tgui/packages/tgui/interfaces/ChemDispenser.js
Recording sucks balls and was added by or*nges, macros are better.
I need someone with TGUI skills to tell me why recipes still show up as this.
:cl:
add: Added the Chemical Macros back to chem dispensers. God bless powergamers.
/:cl:
=> Return of Chemical Macros
