The-Merchants-Guild/Merchant-Station-13

code/game/objects/effects/decals/cleanable/misc.dm
Small chance for vomit to have a name
Because it's funny
:cl:
add: Some vomit may be named after famous trash.
/:cl:
=> Named Vomit

code/modules/projectiles/projectile/bullets/lmg.dm, code/modules/research/designs/mecha_designs.dm, code/modules/vehicles/mecha/equipment/weapons/mecha_ammo.dm, code/modules/vehicles/mecha/equipment/weapons/weapons.dm
**Turns the AC-2 into an actual mech LMG by:**
- Giving it a 15 round burst
- Adjusting the damage per bullet so the DPS is still the same
https://user-images.githubusercontent.com/52262416/128602837-8c3811c2-de3b-4c4b-b7f2-3f24fdd6e07a.mp4
**BRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRT**
=> Makes the mech LMG a mech LMG.

code/modules/wiremod/shell/mech.dm
Fixes #17 , circuit mechs can shoot targets again
Because circuit mechs shooting exclusively north is bad
:cl:
fix: Circuit mechs fire properly at targets again
/:cl:
=> Fix bug where cmech doesn't shoot at target

code/__DEFINES/dcs/signals.dm, code/_compile_options.dm, code/game/machinery/computer/camera.dm
You can now connect cameras with USB ports to bot shells, giving you a click interceptor that gives GPS coordinates (only works when clicking on objects, not tiles)
More USB ports more circuit components more fun, every time
:cl:
add: Security cameras now have an USB port, allowing them to be connected to circuits
/:cl:
=> Circuit cameras

code/game/objects/buckling.dm, code/modules/mob/mob.dm
https://github.com/tgstation/tgstation/pull/60624
=> Fix vehicles

code/controllers/subsystem/discord.dm, code/datums/map_config.dm
thank you TG (for having these issues), very cool.
=> Fix two potential security issues

README.md
:cl:
add: Added new mechanics or gameplay changes
add: Added more things
expansion: Expands content of an existing thing
del: Removed old things
qol: made something easier to use
balance: rebalanced something
fix: fixed a few things
soundadd: added a new sound thingy
sounddel: removed an old sound thingy
imageadd: added some icons and images
imagedel: deleted some icons and images
spellcheck: fixed a few typos
code: changed some code
refactor: refactored some code
config: changed some config setting
admin: messed with admin stuff
server: something server ops should know
/:cl:
=> updating readme mostly to test discord webhook

code/controllers/subsystem/explosions.dm
See this for what you can expect explosion radiuses to be: https://www.desmos.com/calculator/hezcm1ksln
Mathematics are:
`radius^(1/3)+cap`
=> Changes the hard maxcap for explosives to a softcap.

code/modules/deathmatch/deathmatch_controller.dm
This should stop baseturfs from getting broken.
=> Changes deathmatch to use mass delete map generator.

_maps/RandomRuins/IceRuins/icemoon_surface_engioutpost.dmm, _maps/RandomRuins/LavaRuins/lavaland_surface_syndicate_base1.dmm, _maps/RandomRuins/SpaceRuins/hellfactory.dmm, _maps/RandomRuins/SpaceRuins/mrow_thats_right.dmm, _maps/RandomZLevels/SnowCabin.dmm, _maps/RandomZLevels/undergroundoutpost45.dmm, _maps/map_files/Deltastation/DeltaStation2.dmm, _maps/map_files/IceBoxStation/IceBoxStation.dmm, _maps/map_files/IceBoxStation/IcemoonUnderground_Above.dmm, _maps/map_files/KiloStation/KiloStation.dmm, _maps/map_files/MetaStation/MetaStation.dmm, _maps/map_files/tramstation/tramstation.dmm, _maps/shuttles/emergency_cere.dmm, _maps/shuttles/whiteship_box.dmm, _maps/shuttles/whiteship_tram.dmm, code/game/objects/items/circuitboards/machine_circuitboards.dm, code/modules/atmospherics/machinery/components/binary_devices/thermomachine.dm, code/modules/unit_tests/machine_disassembly.dm, tgui/packages/tgui/interfaces/ThermoMachine.js
Not a single person who is even slightly sane actually likes this thing.
=> Reverts the thermomachine.

code/datums/datum.dm, code/game/interfaces.dm, code/game/world.dm, tgstation.dme
Holy shit i wanted this for quite a while, i was wondering for a long time if it was even possible given the shitty preprocessors we have, but it worked! 
Note: i know some goon coder also made interfaces, but i didnt even look at their code. This is 100% original
Fucking interfaces duuuh!
All you have to do to implement the interface is type 
`IMPLEMENTS(<some unique id  you give it, it can be literally whatever, cannot contain special characters>, <the type you are implementing the interfaces at>, <the **name** of the interface>)`
, now if you try to compile, the game should start but immediately runtime and exit, to fix it you need to declare every single interface proc that is not found in the implementing type! You can cast any object to interface by casting it to …
=> INTERFACES: how i stopped worrying and started to love macro abuse

tgui/packages/tgui/interfaces/ThermoMachine.js
aaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
=> Fix thermomachine UI

code/modules/wiremod/components/sensors/computervision.dm
Makes it so computer vision can see objects
Computer vision always was supposed to do this
:cl:
add: Computer Vision can see objects now
/:cl:
=> Computer vision fixes

code/modules/mining/bluespace.dm, tgstation.dme
Adds the bluespace miner. Automatically generates resources slowly while consuming power. Needs bluespace crystals, gold and uranium to be made.
originally made by [Toxici11i](https://github.com/Toxici11i) over on hippie
help why is tgstation.dme there a aa aa
=> Adds bluespace miner

code/datums/wires/explosive.dm, code/modules/assembly/voice.dm
=> makes voice grenades instant again

code/controllers/configuration/entries/general.dm, code/datums/mutations/_combined.dm, code/datums/mutations/sight.dm, code/modules/mob/living/carbon/emote.dm, code/modules/projectiles/guns/energy/energy_gun.dm, code/modules/research/designs/bluespace_designs.dm, interface/interface.dm, interface/skin.dmf
You can make the XRAY mutation again.
Replaced a forum hyperlink to a discord one, add it to the config.
You can sfart in crit(intended)
Thermals are no longer an activatable spell but they are as before.
E-Guns are no longer bulky what the fuck was that change KILL yourself
=> Xray, forum to discord, superfart in crit, thermals revert, e-gun no longer bulky

code/modules/deathmatch/deathmatch_lobby.dm
Still need to figure out how people manage to start games while all players aren't ready.
=> Fix deathmatch start being spammable.

code/modules/research/techweb/all_nodes.dm
=> why is the linter complaning about this now?

_maps/map_files/MetaStation/MetaStation.dmm
I like bigger maints. I expanded maints. I don't need to explain myself, maints are cool.
Maints are cool
:cl:
expansion: Maints expanded
/:cl:
=> Meta maints rework

code/modules/client/flag.dm, tools/ci/check_grep.sh
=> fixes edge's retardation

code/game/gamemodes/dynamic/dynamic.dm
=> fixes the lack of threat reports and alert level upgrading.

code/modules/client/verbs/ooc.dm, code/modules/mining/bluespace.dm, code/modules/research/designs/machine_designs.dm
=> fixes ooc issue and bluespace miner unprintability

code/controllers/configuration/entries/general.dm, code/controllers/subsystem/ticker.dm, code/game/world.dm, code/modules/admin/verbs/server.dm
=> Support for hard server restart

code/__DEFINES/access.dm, code/controllers/subsystem/id_access.dm, code/game/machinery/PDApainter.dm, code/game/machinery/doors/airlock_electronics.dm, code/game/objects/items/cards_ids.dm, code/modules/modular_computers/file_system/programs/card.dm, tgui/packages/tgui/interfaces/AirlockElectronics.js, tgui/packages/tgui/interfaces/NtosCard.js
- airlock access UI works again
- space hotel staff IDs have access now
- refactor UIs slightly.
- PDA painter works again.
=> Fix some ID rework issues.

code/modules/vehicles/mecha/_mecha.dm, code/modules/vehicles/sealed.dm
Non-combat mechs now have their default 5 damage again.
Just a bugfix, 's all.
=> Fixes non-combat mechs not doing damage.

code/__HELPERS/path.dm, code/modules/wiremod/components/action/pathfind.dm
Robots now work properly again!
Credit to: https://github.com/tgstation/tgstation/pull/60751 and https://github.com/tgstation/tgstation/pull/60485
=> Fixes robot pathfinding.

code/modules/vehicles/mecha/mech_fabricator.dm
As it says on the tin, pure QoL.
Credit goes to: https://github.com/tgstation/tgstation/pull/64311
=> Makes mechfabs able to change the output direction.

_maps/RandomRuins/LavaRuins/lavaland_surface_syndicate_base1.dmm
Adds a griddle and some extra meat to the lavaland base for syndies, that's all folks.
Cheers Jin.
=> Gives lavaland syndies something to grill.

code/__DEFINES/machines.dm, code/modules/research/designs/wiremod_designs.dm, code/modules/wiremod/component.dm, code/modules/wiremod/integrated_circuit.dm, tgui/packages/tgui/interfaces/IntegratedCircuit/index.js
Changes integrated circuits (I don't think it works with modules yet, open an issue if you care that much, I don't) to allow you to add components inside without needing a circuit printer. Those components disappear when removed from the circuit. The printer can be hidden by the click of a single button.
Less wasteful clicks, less having to move your massive work window around to retrieve circuits from another machine all the time. All in all, it's a game, not a second job, and there's no reason to make interacting with a game mechanic needlessly frustrating. If you want something like a computer vision component or MMI component you still need to go and grab a circuit printer.
:cl:
expansion: Circuit miniprinter now exists inside integrated circuits, allowing you to no longer waste time …
=> Circuit printer inside integrated circuits

code/modules/research/designs/autolathe_designs.dm
=> Adds the BANG assembly to autolathe.

code/modules/wiremod/components/action/speech.dm
why the fuck was this not sanitized?
=> Sanitize circuits speech component

code/modules/admin/verbs/server.dm
yeaah... this checked for tgs, this is why you test your changes kids.
=> Actually allows admins to hard restart the serber

_maps/map_files/Deltastation/DeltaStation2.dmm, _maps/map_files/IceBoxStation/IceBoxStation.dmm, _maps/map_files/KiloStation/KiloStation.dmm, _maps/map_files/MetaStation/MetaStation.dmm, code/modules/mapping/mapping_helpers.dm
okay, so there was a slight issue with the simple pipe mapping helper that meant it didn't connect to layer manifolds properly. also I have seen some terrible fucking pipe mapping today, I need a moment.
=> Fix layer manifold connections

code/modules/mob/emote.dm
Removes the dumb cool downs from the spin and flip emotes. You won't fall down or get dizzy anymore.
Because spinning and flipping do nothing but look funny
=> spin and flip are fun again

code/modules/mob/living/carbon/human/species.dm
the armstrong pr broke stuff, this fixes it
fuck
:cl:
add: Added new mechanics or gameplay changes
add: Added more things
expansion: Expands content of an existing thing
del: Removed old things
qol: made something easier to use
balance: rebalanced something
fix: fixed a few things
soundadd: added a new sound thingy
sounddel: removed an old sound thingy
imageadd: added some icons and images
imagedel: deleted some icons and images
spellcheck: fixed a few typos
code: changed some code
refactor: refactored some code
config: changed some config setting
admin: messed with admin stuff
server: something server ops should know
/:cl:
=> Fixes hugging and shaking

code/modules/mob/dead/observer/observer.dm
Makes ghosts bob again.
That's all.
=> Fixes ghost bobbing.

code/modules/research/designs/weapon_designs.dm, code/modules/research/techweb/all_nodes.dm
Does what is says on the tin
Security should not have to build and then hack an autolathe to make more of their own lethal shotgun shells that they get at round start
:cl:
-Adds the laser shells from the sec lethal locker to the security department lathe
/:cl:
=> Adds Laser Shells to Sec Lathe

code/game/objects/items/circuitboards/machine_circuitboards.dm, code/game/objects/structures/crates_lockers/closets/secure/hydroponics.dm, code/modules/hydroponics/gene_modder.dm, code/modules/hydroponics/hydroponics.dm, code/modules/hydroponics/plant_genes.dm, code/modules/reagents/chemistry/reagents/food_reagents.dm, code/modules/vending/nutrimax.dm, tgstation.dme
Secateurs are still in as an option for a ghetto hydroponics setup I guess? Removed from the roundstart closets.
I'll PR map changes once this gets merged, I wanna see if there's anything I need to edit first.
:cl:
add: Added the Hydroponics DNA Modder back in.
:cl:
=> Adds the DNA Poopfarter back to hydrogoynics

_maps/map_files/IceBoxStation/IceBoxStation.dmm, _maps/map_files/KiloStation/KiloStation.dmm, _maps/map_files/MetaStation/MetaStation.dmm, code/game/objects/items/storage/boxes.dm, code/game/objects/structures/crates_lockers/closets/secure/hydroponics.dm, code/modules/research/designs/autolathe_designs.dm, code/modules/research/designs/machine_designs.dm, code/modules/research/techweb/all_nodes.dm
poopie
:cl:
add: a bit of poopie? some poopie rapie?
/:cl:
=> Adds plant gene manipulator to techweb and maps, disks to autolathe and closets.

code/game/objects/items/devices/radio/headset.dm
changes literally one line, admins speedmerge this pls
=> Fix: Makes headsets broadcast over subspace network

code/modules/hydroponics/seeds.dm
tceo you retard
:cl:
Fix: Separated chems actually work now.
:cl:
=> Fixes separated chemicals

code/game/machinery/doors/poddoor.dm
Quick fix. Hasn't been tested yet due to me being busy.
I'll test it later on, no worries.
=> fixes mechs opening blast doors and shutters

code/modules/vending/megaseed.dm
Can't have your cake and eat it too.
:cl:
add: Replica Pods added to megaseed vendor.
/:cl:
=> Adds replica pod seeds to the megaseed vendor roundstart.

dependencies.sh, tools/ci/install_rust_g.sh
Updates rust-g version for SSL-encrypted MySQL conenctions
:cl:
fix: update rust-g version for CI
/:cl:
=> Update rust-g dependencies

code/__DEFINES/tgs.dm, code/modules/tgs/README.md, code/modules/tgs/v3210/api.dm, code/modules/tgs/v5/api.dm
This pull request updates the TGS DMAPI to the latest version. Please note any breaking or unimplemented changes before merging.
=> Automatic TGS DMAPI Update

dependencies.sh, tools/tgs4_scripts/PreCompile.sh, tools/tgs4_scripts/PreSynchronize.sh
Does proper sudo'ing for TGS build scripts in the event that not all packages are installed
:cl:
refactor: Do proper sudo'ing of TGS scripts
/:cl:
=> Do proper sudo'ing of TGS scripts

dependencies.sh
Mirrors tgstation/tgstation#64513
=> Last node version to support Win7

code/datums/changelog/changelog.dm
Finally, I've done it. This fixes the changelog on Linux and/or with TGS.
Working changelogs motherfucker!
:cl:
fix: Changelogs work again
/:cl:
=> Fixes the changelog once and for all

html/changelogs/archive/2021-08.yml, html/changelogs/archive/2021-10.yml, html/changelogs/archive/2021-12.yml, html/changelogs/archive/2022-01.yml, html/changelogs/archive/2022-03.yml, html/changelogs/archive/2022-04.yml, html/changelogs/archive/2022-05.yml
Updates the changelogs for all our newfriends to look at, at least for the ones that were formatted properly. (@KangTut @AcapitalA @TheChosenEvilOne better start writing proper fucking CLs, see valid tags in `tools/changelog/tags.yml`)
=> Compiled changelogs for the year we missed [ci skip]

_maps/map_files/Deltastation/DeltaStation2.dmm
As the title says. Closes #190 
:cl:
fix: Deltastation now has a DNA manipulator again.
/:cl:
=> Gives delta botany a DNA manipulator.

.github/MAPS_AND_AWAY_MISSIONS.md, README.md
I mean, about fucking time, right?
(Feel free to suggest any changes to it if you think they're necessary).
=> Update README [ci skip]

code/modules/mob/living/silicon/robot/robot.dm
Take 2 borgs will suffer damage slowdown after taking severe damage just like carbons
Because shut up
=> Borg damage slowdown

code/__DEFINES/economy.dm, code/modules/jobs/job_types/janitor.dm
Changes the janitor's salary to 0 cr.
\>he's a janitor
\>on the internet
\>on an anime imageboard
\>he does it for free
\>he takes his "job" very seriously
\>he does it because it is the only amount of power & control he will ever have in his pathetic life
\>he deletes threads he doesn't like because whenever he gets upset he has an asthma attack
\>he deletes threads he doesn't like because they interfere with the large backlog of little girl chinese cartoons he still has to watch
\>he will never have a real job
\>he will never move out of his parent's house
\>he will never be at a healthy weight
\>he will never know how to cook anything besides a hot pocket
\>he will never have a girlfriend
\>he will never have any friends
:cl:
balance: He does it for free
/:cl:
=> He does it for free

code/datums/components/storage/concrete/extract_inventory.dm, code/modules/research/xenobiology/crossbreeding/reproductive.dm, tgstation.dme
closes:https://github.com/The-Merchants-Guild/Merchant-Station-13/issues/206
took it from:https://github.com/tgstation/tgstation/pull/60345
bug fix
:cl:
fix: fixed you are able to feed reproductive extracts with biobags again
/:cl:
=> You can feed reproductives extracts with biobag again

code/modules/research/designs/biogenerator_designs.dm
poonis rartus
:cl:
add: Biogenerators can now finally produce strange seeds for the low low cost of...SIX HUNDRED BIOMASS?
/:cl:
=> Adds strange seeds to the botany biogenerator

code/modules/atmospherics/machinery/portable/pump.dm
title says it all
you can now make ttv as god intended
🆑 
del: Removed portable pump pressure and heat limit 
/🆑
=> Removing the portable pump pressure and heat limit

code/modules/deathmatch/deathmatch_lobby.dm
Creates a new mind for deathmatch players. closes #220.
:cl:
fix: Deathmatch now properly cleans up special statuses and such from players.
/:cl:
=> Clean up deathmatch player mind properly.

code/modules/vending/cigarette.dm
We added weed to the cigarette vending machines... and all it took was 500 dollars a month...
:cl:
add: 420station lmaoooo
/:cl:
=> 420station

SQL/tgstation_schema_prefixed.sql, code/modules/admin/verbs/adminhelp.dm
SQL fixes. (Players with open ahelps leaving the game caused an SQL error)
:cl:
admin: stop bugging me about SQL errors please
/:cl:
=> Fixed prefixed schema, fixed SQL errors

.github/workflows/ci_suite.yml
GitHub broke CI I think. Nobody seems to know why. This apparently fixes it?
=> Fix CI Linter Errors

code/modules/surgery/surgery_step.dm
closes:https://github.com/The-Merchants-Guild/Merchant-Station-13/issues/224
You can do surgery on your head again
:cl:
fix: self surgery on head works again
/:cl:
=> You can use self surgery on head again

code/modules/clothing/spacesuits/hardsuit.dm
3 units put you to sleep lol
:cl:
balance: The HEV Suit now injects you with less morphine. Hevsuit now slows you down by a small amount.
/:cl:
=> Hevsuit rebalancing.

code/modules/admin/verbs/ert.dm
:cl:
fix: Fixed admin ERT spawning for preset ERTs
admin: Admin ERT spawning now gives the admin more feedback, like it did previously.
/:cl:
=> ERT fix + tweaks

code/modules/surgery/organ_manipulation.dm
Title.
Bugfix.
:cl:
fix: DRM in NanoTrasen-Issue Prosthetic Legs:tm: (Patent Pending) has been modified to allow station surgeons to perform organ manipulation on them.
/:cl:
=> Allow organ manipulation on prosthetic legs.

code/modules/modular_computers/file_system/programs/wbcontroller.dm, code/modules/surgery/organs/cybernetics/augments_internal_wordblock.dm
=> Wordblocker fixes.

code/datums/ert.dm
:cl:
fix: ERTs loaded from file no longer get an extra Centcom Official antagonist.
/:cl:
=> ERT Fix 2: Electric Boogaloo

_maps/map_files/DM/Maint_Mania.dmm
YOU FUCKING REMOVED A WINDOW ON THE OUTSIDE YOU COCKSUCKER
:cl:
fix: restores the windows one of our gypsy shitcoders stole
/:cl:
=> Fixes escaping the DM(I hope) Part 2: Fuck you Lunaman edition

code/game/objects/items/food/meat.dm, code/modules/food_and_drinks/food/condiment.dm, code/modules/reagents/chemistry/reagents/drink_reagents.dm
Changes description of soymilk, tofu, any food I could find that involves estrogen. If I missed any other soy products or if you think you can come up with better descriptions, please let me know (or just change it yourself).
Untested, but all I changed was some descriptions, so if this is somehow bad there has to be some serious fuckery in the code.
No one likes tofu.
:cl:
add: Soymilk description changed to something more befitting.
/:cl:
=> Changes soy product descriptions

code/modules/research/designs/weapon_designs.dm, code/modules/research/techweb/all_nodes.dm
:cl:
add: Re-added the syringe gun and rapid syringe gun to the normal research tree. No more Syndicate tech requirement.
/:cl:
=> Adds the syringe gun and rapid version to normal research again.

code/modules/hydroponics/grown/buttflower.dm, code/modules/mob/living/carbon/emote.dm, code/modules/vending/megaseed.dm
Also a bugfix.
:cl:
add: Farts now smell quite badly! Don't get pink eye!
add: Buttplants now have a specific odour to them. 
add: Buttplants are now actually purchasable from a hacked Plant Vendor.
/:cl:
=> Farts spawn miasma.

_maps/map_files/Deltastation/DeltaStation2.dmm, _maps/map_files/KiloStation/KiloStation.dmm
Gunshop didnt spawn in delta and kilo hopefully now it will
:cl:
fix: gun shop spawns in delta and kilo like it was supposed to
/:cl:
=> fixes gunshop not spawning in delta and kilo hopefully
